<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ArcEngineC_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Shaders\basic.frag" />
    <None Remove="Assets\Shaders\basic.vert" />
    <None Remove="Assets\Textures\test.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Shaders\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Textures\test.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Models\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
    <PackageReference Include="SharpGLTF.Core" Version="1.0.6" />
    <PackageReference Include="BepuPhysics" Version="2.4.0" />
    <PackageReference Include="Hexa.NET.ImGui" Version="2.1.10" />
    <PackageReference Include="Hexa.NET.ImGuizmo" Version="2.1.10" />
  </ItemGroup>

</Project>
